# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scs_user', '0002_auto_20161105_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.TextField(default='Set Your Username'),
        ),
    ]
