# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scs_user', '0004_auto_20161113_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.TextField(default='Edit Profile', max_length=1000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='branch',
            field=models.CharField(default='Computer Science Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='college',
            field=models.CharField(default='Sant Longowal Institute of Engineering and Technology', max_length=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
