# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='catagory',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 9, 8, 39, 142000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
